{
  "formatVersion": "1.1",
  "component": {
    "group": "org.bitbuckets",
    "module": "simulator-rev",
    "version": "2020.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "srgrlxd6ova3zffnzrt2ilcnde"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.revrobotics.frc",
          "module": "SparkMax-java",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.bitbuckets",
          "module": "simulator",
          "version": {
            "requires": "2020.1.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-rev-2020.1.2-SNAPSHOT.jar",
          "url": "simulator-rev-2020.1.2-SNAPSHOT.jar",
          "size": 5698,
          "sha512": "c5b93ede46ad53ce32548c2c7c429074efbdd5f4c75a8e27df3586cd0c0b4ef61f27e84803596e1d2ed06b24e5433d947fb320988681eeb3be2470f18b1a9e15",
          "sha256": "437ff92028994aa9a275f3925f2e5a61dd7038f9e4af1177731a767780b0058b",
          "sha1": "9f43f6f24341283448246e608a2f842a508fc38f",
          "md5": "4906971e45f8742c854a6ba29d2bb147"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.revrobotics.frc",
          "module": "SparkMax-java",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.bitbuckets",
          "module": "simulator",
          "version": {
            "requires": "2020.1.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-rev-2020.1.2-SNAPSHOT.jar",
          "url": "simulator-rev-2020.1.2-SNAPSHOT.jar",
          "size": 5698,
          "sha512": "c5b93ede46ad53ce32548c2c7c429074efbdd5f4c75a8e27df3586cd0c0b4ef61f27e84803596e1d2ed06b24e5433d947fb320988681eeb3be2470f18b1a9e15",
          "sha256": "437ff92028994aa9a275f3925f2e5a61dd7038f9e4af1177731a767780b0058b",
          "sha1": "9f43f6f24341283448246e608a2f842a508fc38f",
          "md5": "4906971e45f8742c854a6ba29d2bb147"
        }
      ]
    }
  ]
}
