{
  "formatVersion": "1.1",
  "component": {
    "group": "org.bitbuckets",
    "module": "simulator-rev",
    "version": "2020.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "cuqddndiancsxbt5p564bor3tu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.revrobotics.frc",
          "module": "SparkMax-java",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.bitbuckets",
          "module": "simulator",
          "version": {
            "requires": "2020.1.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-rev-2020.1.2-SNAPSHOT.jar",
          "url": "simulator-rev-2020.1.2-SNAPSHOT.jar",
          "size": 5698,
          "sha512": "48cd9d78a72862e9c8691c05767742299ebfe52a5ee1c3d65a32eff0bf71aca19435a0b98a98e67f9f90aebc642d674625644d8340ae52b10153ad7eeb492f25",
          "sha256": "3fb0ccc9de849c7ceb031277149f2007a2bf91868d4d5bd6e427ddad451159f2",
          "sha1": "9623cd77a39cbb83b58a9778f6e4640c97f2d123",
          "md5": "a92c5b6e19840cc0a9c8d84559527e6d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.revrobotics.frc",
          "module": "SparkMax-java",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.bitbuckets",
          "module": "simulator",
          "version": {
            "requires": "2020.1.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-rev-2020.1.2-SNAPSHOT.jar",
          "url": "simulator-rev-2020.1.2-SNAPSHOT.jar",
          "size": 5698,
          "sha512": "48cd9d78a72862e9c8691c05767742299ebfe52a5ee1c3d65a32eff0bf71aca19435a0b98a98e67f9f90aebc642d674625644d8340ae52b10153ad7eeb492f25",
          "sha256": "3fb0ccc9de849c7ceb031277149f2007a2bf91868d4d5bd6e427ddad451159f2",
          "sha1": "9623cd77a39cbb83b58a9778f6e4640c97f2d123",
          "md5": "a92c5b6e19840cc0a9c8d84559527e6d"
        }
      ]
    }
  ]
}
