{
  "formatVersion": "1.1",
  "component": {
    "group": "org.bitbuckets",
    "module": "simulator-rev",
    "version": "2020.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "v7a3m6pphnbjriti5tvzjn2qyq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.revrobotics.frc",
          "module": "SparkMax-java",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.bitbuckets",
          "module": "simulator",
          "version": {
            "requires": "2020.1.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-rev-2020.1.2-SNAPSHOT.jar",
          "url": "simulator-rev-2020.1.2-SNAPSHOT.jar",
          "size": 5698,
          "sha512": "22602db419320260303381ae08f93f2b6b66cfa5dc09077c5ec9498c0e3d28bf6b053a5e8bd24718f9137dde35ae54fb54863f3bc680651913898dc64053a5f6",
          "sha256": "56579425f1b87867563a2cc2b85551288f76cbc98ef46e81c3ba65b1206f106e",
          "sha1": "71bebfa08f951cd2bcf7129efa4ab0ca07e4b156",
          "md5": "34db94381accfbdafa88a4bf63ede18a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.revrobotics.frc",
          "module": "SparkMax-java",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.bitbuckets",
          "module": "simulator",
          "version": {
            "requires": "2020.1.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-rev-2020.1.2-SNAPSHOT.jar",
          "url": "simulator-rev-2020.1.2-SNAPSHOT.jar",
          "size": 5698,
          "sha512": "22602db419320260303381ae08f93f2b6b66cfa5dc09077c5ec9498c0e3d28bf6b053a5e8bd24718f9137dde35ae54fb54863f3bc680651913898dc64053a5f6",
          "sha256": "56579425f1b87867563a2cc2b85551288f76cbc98ef46e81c3ba65b1206f106e",
          "sha1": "71bebfa08f951cd2bcf7129efa4ab0ca07e4b156",
          "md5": "34db94381accfbdafa88a4bf63ede18a"
        }
      ]
    }
  ]
}
