{
  "formatVersion": "1.1",
  "component": {
    "group": "org.bitbuckets",
    "module": "simulator-ctre",
    "version": "2020.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "sbfaqlugsvhzhmj2kl7w43xidu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.ctre.phoenix",
          "module": "api-java",
          "version": {
            "requires": "5.17.6"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "wpiapi-java",
          "version": {
            "requires": "5.17.6"
          }
        },
        {
          "group": "org.bitbuckets",
          "module": "simulator",
          "version": {
            "requires": "2020.1.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-ctre-2020.1.2-SNAPSHOT.jar",
          "url": "simulator-ctre-2020.1.2-SNAPSHOT.jar",
          "size": 6905,
          "sha512": "99c978470937bfd47b584049a553741e58f1776bb43759d590718bd1c0c81d5640036591b58c065a9fb9c68f73f6e58eb5a732751c791d221a0f00b9ba03c839",
          "sha256": "1a83ac578087b9d3be3f36c9eff0946c41e469f3addee4842a4863c42c151f07",
          "sha1": "e3c2101b7d62ce82142cad3c3b0c05698abb1d21",
          "md5": "b4247c8337b1c9c8468936be2287d979"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.ctre.phoenix",
          "module": "api-java",
          "version": {
            "requires": "5.17.6"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "wpiapi-java",
          "version": {
            "requires": "5.17.6"
          }
        },
        {
          "group": "org.bitbuckets",
          "module": "simulator",
          "version": {
            "requires": "2020.1.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-ctre-2020.1.2-SNAPSHOT.jar",
          "url": "simulator-ctre-2020.1.2-SNAPSHOT.jar",
          "size": 6905,
          "sha512": "99c978470937bfd47b584049a553741e58f1776bb43759d590718bd1c0c81d5640036591b58c065a9fb9c68f73f6e58eb5a732751c791d221a0f00b9ba03c839",
          "sha256": "1a83ac578087b9d3be3f36c9eff0946c41e469f3addee4842a4863c42c151f07",
          "sha1": "e3c2101b7d62ce82142cad3c3b0c05698abb1d21",
          "md5": "b4247c8337b1c9c8468936be2287d979"
        }
      ]
    }
  ]
}
