{
  "formatVersion": "1.1",
  "component": {
    "group": "org.bitbuckets",
    "module": "simulator-ctre",
    "version": "2020.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "lao7oq66znglpkwjmaqhd7jeue"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.ctre.phoenix",
          "module": "api-java",
          "version": {
            "requires": "5.17.6"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "wpiapi-java",
          "version": {
            "requires": "5.17.6"
          }
        },
        {
          "group": "org.bitbuckets",
          "module": "simulator",
          "version": {
            "requires": "2020.1.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-ctre-2020.1.2-SNAPSHOT.jar",
          "url": "simulator-ctre-2020.1.2-SNAPSHOT.jar",
          "size": 6905,
          "sha512": "b138f3f3bac1ab2b1526554c97e93b4f7983b973a02268ec569ab09899b8094d8220f8b867724705d462fcc980ea09d56232be7e09321ea0429261ba7b953364",
          "sha256": "83abb2ee539a05952c43c64ebf50e0200cacb66cb19e70f2c429f6321c520ca5",
          "sha1": "7d91a07247e0e88f3972b5b4a4d1d50b37a50b9f",
          "md5": "1dcddd92a0eba6dec79ac8ba3cefe2e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.ctre.phoenix",
          "module": "api-java",
          "version": {
            "requires": "5.17.6"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "wpiapi-java",
          "version": {
            "requires": "5.17.6"
          }
        },
        {
          "group": "org.bitbuckets",
          "module": "simulator",
          "version": {
            "requires": "2020.1.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-ctre-2020.1.2-SNAPSHOT.jar",
          "url": "simulator-ctre-2020.1.2-SNAPSHOT.jar",
          "size": 6905,
          "sha512": "b138f3f3bac1ab2b1526554c97e93b4f7983b973a02268ec569ab09899b8094d8220f8b867724705d462fcc980ea09d56232be7e09321ea0429261ba7b953364",
          "sha256": "83abb2ee539a05952c43c64ebf50e0200cacb66cb19e70f2c429f6321c520ca5",
          "sha1": "7d91a07247e0e88f3972b5b4a4d1d50b37a50b9f",
          "md5": "1dcddd92a0eba6dec79ac8ba3cefe2e7"
        }
      ]
    }
  ]
}
