{
  "formatVersion": "1.1",
  "component": {
    "group": "org.bitbuckets",
    "module": "simulator-ctre",
    "version": "2020.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "q2axthk63newxknrcn4yb2zej4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.ctre.phoenix",
          "module": "api-java",
          "version": {
            "requires": "5.17.6"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "wpiapi-java",
          "version": {
            "requires": "5.17.6"
          }
        },
        {
          "group": "org.bitbuckets",
          "module": "simulator",
          "version": {
            "requires": "2020.1.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-ctre-2020.1.2-SNAPSHOT.jar",
          "url": "simulator-ctre-2020.1.2-SNAPSHOT.jar",
          "size": 6905,
          "sha512": "c2ade9e88cdf383a7ec1408160ebd88fd8381367d24e83aec87fd268d56f03c783ac79e5029e09a450351edb6ca3ca3d34019c7a2ca0a672a867bd3bd8bf6f3b",
          "sha256": "7cd3e205a4a20fde16753bfc4d3d792bd5cd84759148a9503c1e956922d64ad1",
          "sha1": "16cb272caba91cd3ba8e89f416077c7cf734c405",
          "md5": "4e5f5f37d04a179827044087df74a861"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.ctre.phoenix",
          "module": "api-java",
          "version": {
            "requires": "5.17.6"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "wpiapi-java",
          "version": {
            "requires": "5.17.6"
          }
        },
        {
          "group": "org.bitbuckets",
          "module": "simulator",
          "version": {
            "requires": "2020.1.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "simulator-ctre-2020.1.2-SNAPSHOT.jar",
          "url": "simulator-ctre-2020.1.2-SNAPSHOT.jar",
          "size": 6905,
          "sha512": "c2ade9e88cdf383a7ec1408160ebd88fd8381367d24e83aec87fd268d56f03c783ac79e5029e09a450351edb6ca3ca3d34019c7a2ca0a672a867bd3bd8bf6f3b",
          "sha256": "7cd3e205a4a20fde16753bfc4d3d792bd5cd84759148a9503c1e956922d64ad1",
          "sha1": "16cb272caba91cd3ba8e89f416077c7cf734c405",
          "md5": "4e5f5f37d04a179827044087df74a861"
        }
      ]
    }
  ]
}
