{
  "formatVersion": "1.1",
  "component": {
    "group": "org.bitbuckets",
    "module": "simulator",
    "version": "2020.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qfnwh2pqtzgnpj2t7hfb4ldg4m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2020.3.2"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2020.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2020.3.2"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2020.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "3.4.7-2"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2020.3.2"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2020.3.2"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2020.3.2"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.38"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.kauailabs.navx.frc",
          "module": "navx-java",
          "version": {
            "requires": "3.1.400"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.25"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "com.hubspot.jinjava",
          "module": "jinjava",
          "version": {
            "requires": "2.4.15"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.2.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "guice",
              "type": "jar",
              "extension": "jar",
              "classifier": "no_aop"
            }
          }
        },
        {
          "group": "uk.co.electronstudio.sdl2gdx",
          "module": "sdl2gdx",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-box2d",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-controllers",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-backend-lwjgl",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-platform",
          "version": {
            "requires": "1.9.10"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gdx-platform",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-desktop"
            }
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-box2d-platform",
          "version": {
            "requires": "1.9.10"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gdx-box2d-platform",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-desktop"
            }
          }
        }
      ],
      "files": [
        {
          "name": "simulator-2020.1.2-SNAPSHOT.jar",
          "url": "simulator-2020.1.2-SNAPSHOT.jar",
          "size": 1769258,
          "sha512": "840db33f175aaefc83df647c1a235a2c5cb69fefb8c9b711092402b4acb708bbdccb9cf21cad9355b201adfd6dafe822f339440fc6fe7973d22228f107008877",
          "sha256": "e97a8c6af906e914a0cd900d0d69369d2dcfb10cee0a91f5a2fd9d44d44d190d",
          "sha1": "b1e76df8036e45fdb73cdbb4771f37948c58deab",
          "md5": "12cd9c0f4589a1e3fd1bc540ec09413c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.grpc",
          "module": "grpc-netty-shaded",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2020.3.2"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2020.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2020.3.2"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2020.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "3.4.7-2"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2020.3.2"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2020.3.2"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2020.3.2"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.38"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.kauailabs.navx.frc",
          "module": "navx-java",
          "version": {
            "requires": "3.1.400"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.25"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "com.hubspot.jinjava",
          "module": "jinjava",
          "version": {
            "requires": "2.4.15"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.2.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "guice",
              "type": "jar",
              "extension": "jar",
              "classifier": "no_aop"
            }
          }
        },
        {
          "group": "uk.co.electronstudio.sdl2gdx",
          "module": "sdl2gdx",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-box2d",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-controllers",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-backend-lwjgl",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-platform",
          "version": {
            "requires": "1.9.10"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gdx-platform",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-desktop"
            }
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-box2d-platform",
          "version": {
            "requires": "1.9.10"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gdx-box2d-platform",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-desktop"
            }
          }
        }
      ],
      "files": [
        {
          "name": "simulator-2020.1.2-SNAPSHOT.jar",
          "url": "simulator-2020.1.2-SNAPSHOT.jar",
          "size": 1769258,
          "sha512": "840db33f175aaefc83df647c1a235a2c5cb69fefb8c9b711092402b4acb708bbdccb9cf21cad9355b201adfd6dafe822f339440fc6fe7973d22228f107008877",
          "sha256": "e97a8c6af906e914a0cd900d0d69369d2dcfb10cee0a91f5a2fd9d44d44d190d",
          "sha1": "b1e76df8036e45fdb73cdbb4771f37948c58deab",
          "md5": "12cd9c0f4589a1e3fd1bc540ec09413c"
        }
      ]
    }
  ]
}
