{
  "formatVersion": "1.1",
  "component": {
    "group": "org.bitbuckets",
    "module": "simulator",
    "version": "2020.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "u3srds2axrfnncwmnbjjp3w74m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2020.2.2"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2020.2.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2020.2.2"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2020.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "3.4.7-2"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2020.2.2"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2020.2.2"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2020.2.2"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.38"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.kauailabs.navx.frc",
          "module": "navx-java",
          "version": {
            "requires": "3.1.400"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.25"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "com.hubspot.jinjava",
          "module": "jinjava",
          "version": {
            "requires": "2.4.15"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.2.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "guice",
              "type": "jar",
              "extension": "jar",
              "classifier": "no_aop"
            }
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-box2d",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-controllers",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-backend-lwjgl",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-platform",
          "version": {
            "requires": "1.9.10"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gdx-platform",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-desktop"
            }
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-box2d-platform",
          "version": {
            "requires": "1.9.10"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gdx-box2d-platform",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-desktop"
            }
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-controllers-desktop",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-controllers-platform",
          "version": {
            "requires": "1.9.10"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gdx-controllers-platform",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-desktop"
            }
          }
        }
      ],
      "files": [
        {
          "name": "simulator-2020.1.2-SNAPSHOT.jar",
          "url": "simulator-2020.1.2-SNAPSHOT.jar",
          "size": 1009073,
          "sha512": "3e018549e73fbcf0b16556f6a36c9022d9baeac49b1724c7b4795b8895b449dc9d1ef37e45a6625bc1955da44701b8827e11155c59d70baa94a9d6cbd813358c",
          "sha256": "aa2dfafba0208217f4fb4385796c87251d4affd4f0a40030d2ef84c5345e16e5",
          "sha1": "1b45e8dd0c445b2c67065a0d70ab1ff5c7d47c3d",
          "md5": "440c61acc200a3a62f4daa0ffe608489"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.grpc",
          "module": "grpc-netty-shaded",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2020.2.2"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2020.2.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2020.2.2"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2020.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "3.4.7-2"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2020.2.2"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2020.2.2"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2020.2.2"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.38"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.kauailabs.navx.frc",
          "module": "navx-java",
          "version": {
            "requires": "3.1.400"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.25"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "com.hubspot.jinjava",
          "module": "jinjava",
          "version": {
            "requires": "2.4.15"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.2.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "guice",
              "type": "jar",
              "extension": "jar",
              "classifier": "no_aop"
            }
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-box2d",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-controllers",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-backend-lwjgl",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-platform",
          "version": {
            "requires": "1.9.10"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gdx-platform",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-desktop"
            }
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-box2d-platform",
          "version": {
            "requires": "1.9.10"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gdx-box2d-platform",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-desktop"
            }
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-controllers-desktop",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-controllers-platform",
          "version": {
            "requires": "1.9.10"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gdx-controllers-platform",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-desktop"
            }
          }
        }
      ],
      "files": [
        {
          "name": "simulator-2020.1.2-SNAPSHOT.jar",
          "url": "simulator-2020.1.2-SNAPSHOT.jar",
          "size": 1009073,
          "sha512": "3e018549e73fbcf0b16556f6a36c9022d9baeac49b1724c7b4795b8895b449dc9d1ef37e45a6625bc1955da44701b8827e11155c59d70baa94a9d6cbd813358c",
          "sha256": "aa2dfafba0208217f4fb4385796c87251d4affd4f0a40030d2ef84c5345e16e5",
          "sha1": "1b45e8dd0c445b2c67065a0d70ab1ff5c7d47c3d",
          "md5": "440c61acc200a3a62f4daa0ffe608489"
        }
      ]
    }
  ]
}
