{
  "formatVersion": "1.1",
  "component": {
    "group": "org.bitbuckets",
    "module": "simulator",
    "version": "2020.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "nhrflg36rvbhtnobrt3ju6ci4m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2020.3.2"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2020.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2020.3.2"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2020.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "3.4.7-2"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2020.3.2"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2020.3.2"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2020.3.2"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.38"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.kauailabs.navx.frc",
          "module": "navx-java",
          "version": {
            "requires": "3.1.400"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.25"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "com.hubspot.jinjava",
          "module": "jinjava",
          "version": {
            "requires": "2.4.15"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.2.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "guice",
              "type": "jar",
              "extension": "jar",
              "classifier": "no_aop"
            }
          }
        },
        {
          "group": "uk.co.electronstudio.sdl2gdx",
          "module": "sdl2gdx",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-box2d",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-controllers",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-backend-lwjgl",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-platform",
          "version": {
            "requires": "1.9.10"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gdx-platform",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-desktop"
            }
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-box2d-platform",
          "version": {
            "requires": "1.9.10"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gdx-box2d-platform",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-desktop"
            }
          }
        }
      ],
      "files": [
        {
          "name": "simulator-2020.1.2-SNAPSHOT.jar",
          "url": "simulator-2020.1.2-SNAPSHOT.jar",
          "size": 1769377,
          "sha512": "d4daec56bd7d593a7fe380b86e26243a3ca85e06521131aaedaf779a784736dca427f516cf0fd5129658fba3efa78ab628b1b76f299edcd8c3eca04b175a25ba",
          "sha256": "350b482de2164f376204b72376d62c9a1e0bb587ebde299f0685f0356d47c444",
          "sha1": "507005fe31e92a3b2f243749d44ac1b04bcfbbcc",
          "md5": "306c7a55ed0e716a2043a6f23adc67ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.grpc",
          "module": "grpc-netty-shaded",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2020.3.2"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2020.3.2"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2020.3.2"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2020.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "3.4.7-2"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2020.3.2"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2020.3.2"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2020.3.2"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.38"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.kauailabs.navx.frc",
          "module": "navx-java",
          "version": {
            "requires": "3.1.400"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.25"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "com.hubspot.jinjava",
          "module": "jinjava",
          "version": {
            "requires": "2.4.15"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.2.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "guice",
              "type": "jar",
              "extension": "jar",
              "classifier": "no_aop"
            }
          }
        },
        {
          "group": "uk.co.electronstudio.sdl2gdx",
          "module": "sdl2gdx",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-box2d",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-controllers",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-backend-lwjgl",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-platform",
          "version": {
            "requires": "1.9.10"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gdx-platform",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-desktop"
            }
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-box2d-platform",
          "version": {
            "requires": "1.9.10"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gdx-box2d-platform",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-desktop"
            }
          }
        }
      ],
      "files": [
        {
          "name": "simulator-2020.1.2-SNAPSHOT.jar",
          "url": "simulator-2020.1.2-SNAPSHOT.jar",
          "size": 1769377,
          "sha512": "d4daec56bd7d593a7fe380b86e26243a3ca85e06521131aaedaf779a784736dca427f516cf0fd5129658fba3efa78ab628b1b76f299edcd8c3eca04b175a25ba",
          "sha256": "350b482de2164f376204b72376d62c9a1e0bb587ebde299f0685f0356d47c444",
          "sha1": "507005fe31e92a3b2f243749d44ac1b04bcfbbcc",
          "md5": "306c7a55ed0e716a2043a6f23adc67ff"
        }
      ]
    }
  ]
}
